In [2]:
import json
import pandas as pd
from job_agents.generate_titles import generate_titles

In [3]:
df = pd.read_csv("data/jobs_en_5k.csv")

In [5]:
inputs = df[["Unique ID", "Original title"]].rename(columns={"Unique ID": "id", "Original title": "raw title"}).to_dict("records")

In [28]:
def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

In [ ]:
results, all_tokens = [], []

In [43]:
for titles in chunks(inputs[3310:], 10):
    output, n_tokens = await generate_titles(str(titles))
    results += output
    all_tokens.append(n_tokens)
    print(f"processed {len(results)} titles")

Number of input tokens:  622
Number of output tokens:  566
processed 3309 titles
Number of input tokens:  585
Number of output tokens:  518
processed 3319 titles
Number of input tokens:  615
Number of output tokens:  550
processed 3329 titles
Number of input tokens:  594
Number of output tokens:  536
processed 3339 titles
Number of input tokens:  624
Number of output tokens:  562
processed 3349 titles
Number of input tokens:  618
Number of output tokens:  584
processed 3359 titles
Number of input tokens:  619
Number of output tokens:  571
processed 3369 titles
Number of input tokens:  594
Number of output tokens:  532
processed 3379 titles
Number of input tokens:  598
Number of output tokens:  537
processed 3389 titles
Number of input tokens:  621
Number of output tokens:  561
processed 3399 titles
Number of input tokens:  597
Number of output tokens:  531
processed 3409 titles
Number of input tokens:  617
Number of output tokens:  579
processed 3419 titles
Number of input tokens:  614
Number of output tokens:  569
processed 3429 titles
Number of input tokens:  615
Number of output tokens:  549
processed 3439 titles
Number of input tokens:  633
Number of output tokens:  571
processed 3449 titles
Number of input tokens:  627
Number of output tokens:  562
processed 3459 titles
Number of input tokens:  605
Number of output tokens:  544
processed 3469 titles
Number of input tokens:  601
Number of output tokens:  528
processed 3479 titles
Number of input tokens:  601
Number of output tokens:  538
processed 3489 titles
Number of input tokens:  630
Number of output tokens:  558
processed 3499 titles
Number of input tokens:  619
Number of output tokens:  550
processed 3509 titles
Number of input tokens:  576
Number of output tokens:  506
processed 3519 titles
Number of input tokens:  606
Number of output tokens:  536
processed 3529 titles
Number of input tokens:  617
Number of output tokens:  566
processed 3539 titles
Number of input tokens:  606
Number of output tokens:  560
processed 3549 titles
Number of input tokens:  597
Number of output tokens:  542
processed 3559 titles
Number of input tokens:  613
Number of output tokens:  557
processed 3569 titles
Number of input tokens:  592
Number of output tokens:  552
processed 3579 titles
Number of input tokens:  619
Number of output tokens:  598
processed 3589 titles
Number of input tokens:  601
Number of output tokens:  549
processed 3599 titles
Number of input tokens:  611
Number of output tokens:  548
processed 3609 titles
Number of input tokens:  598
Number of output tokens:  530
processed 3619 titles
Number of input tokens:  622
Number of output tokens:  567
processed 3629 titles
Number of input tokens:  587
Number of output tokens:  534
processed 3639 titles
Number of input tokens:  590
Number of output tokens:  524
processed 3649 titles
Number of input tokens:  596
Number of output tokens:  532
processed 3659 titles
Number of input tokens:  596
Number of output tokens:  538
processed 3669 titles
Number of input tokens:  613
Number of output tokens:  547
processed 3679 titles
Number of input tokens:  608
Number of output tokens:  559
processed 3689 titles
Number of input tokens:  618
Number of output tokens:  573
processed 3699 titles
Number of input tokens:  615
Number of output tokens:  556
processed 3709 titles
Number of input tokens:  602
Number of output tokens:  551
processed 3719 titles
Number of input tokens:  572
Number of output tokens:  527
processed 3729 titles
Number of input tokens:  584
Number of output tokens:  519
processed 3739 titles
Number of input tokens:  595
Number of output tokens:  540
processed 3749 titles
Number of input tokens:  602
Number of output tokens:  541
processed 3759 titles
Number of input tokens:  605
Number of output tokens:  552
processed 3769 titles
Number of input tokens:  628
Number of output tokens:  562
processed 3779 titles
Number of input tokens:  593
Number of output tokens:  541
processed 3789 titles
Number of input tokens:  602
Number of output tokens:  577
processed 3799 titles
Number of input tokens:  601
Number of output tokens:  539
processed 3809 titles
Number of input tokens:  620
Number of output tokens:  560
processed 3819 titles
Number of input tokens:  593
Number of output tokens:  522
processed 3829 titles
Number of input tokens:  607
Number of output tokens:  551
processed 3839 titles
Number of input tokens:  591
Number of output tokens:  533
processed 3849 titles
Number of input tokens:  602
Number of output tokens:  534
processed 3859 titles
Number of input tokens:  602
Number of output tokens:  542
processed 3869 titles
Number of input tokens:  613
Number of output tokens:  556
processed 3879 titles
Number of input tokens:  607
Number of output tokens:  519
processed 3888 titles

In [45]:
df_gold = pd.DataFrame(results)

In [48]:
df_gold[df_gold["title name"] == "Sales Representative"]

,id,raw title,title name,span,seniority
118,6417911604,Acute Care Sales Representative,Sales Representative,Acute Care Sales Representative,None
397,6418038006,Associate Sales Rep - ONC - Great Lakes,Sales Representative,Sales Representative,None
398,6418037995,Associate Sales Representative - ONC - Plains,Sales Representative,Sales Representative,None
403,6417986811,"Associate, Sales Representative",Sales Representative,Sales Representative,None
547,6420633772,Call Center Sales Outbound Rep (Bilingual Span...,Sales Representative,Sales Representative,None
857,6420041865,Customer sales service representative front co...,Sales Representative,Sales Representative,None
1577,6418201482,Inside Sales Representative,Sales Representative,Sales Representative,None
2225,6427448410,Outside Sales Rep - ADESA Auto Auction,Sales Representative,Sales Representative,None
2226,6418037555,Outside Sales Rep (32263),Sales Representative,Sales Representative,None
2227,6417889233,Outside Sales Representative,Sales Representative,Sales Representative,None
2228,6417887221,Outside Sales Representative (Bilingual Spanish),Sales Representative,Sales Representative,None
2319,6418022470,Pharmaceutical Sales Representative,Sales Representative,Sales Representative,None
2618,6418119002,Reconstruction Associate Sales Representative ...,Sales Representative,Sales Representative,None
2864,6418028253,"Sales HealthCare - Framingham, MA - Great pay ...",Sales Representative,Sales Representative,None
2873,6420575644,"Sales Rep - Combo - Spokane, WA",Sales Representative,Sales Rep,None
2874,6418045769,"Sales Rep/Outreach Partner - Brockton, MA",Sales Representative,Sales Rep,None
2875,6418204520,Sales Representative,Sales Representative,Sales Representative,None
2876,6417855007,Sales Representative,Sales Representative,Sales Representative,None
2877,6418206446,Sales Representative,Sales Representative,Sales Representative,None
2878,6417902710,Sales Representative,Sales Representative,Sales Representative,None
2879,6417926264,Sales Representative,Sales Representative,Sales Representative,None
2880,6418003910,Sales Representative - Financial Institutions,Sales Representative,Sales Representative,None
2881,6417921254,Sales Representative - Membership,Sales Representative,Sales Representative,None
2882,6418003855,Sales Representative - Relationship Manager,Sales Representative,Sales Representative,None
2883,6417930955,Sales Representative (55722),Sales Representative,Sales Representative,None
2884,6418003908,Sales Representatives - Financial Representative,Sales Representative,Sales Representative,None
2965,6423514588,"Senior Associate, Sales Representative",Sales Representative,Sales Representative,Senior
3244,6418155445,SKE Sales Rep,Sales Representative,Sales Rep,None

In [49]:
pd.DataFrame(results).to_csv("results.csv", index=False)

In [36]:
pd.DataFrame(all_tokens).sum()

0    200084
1    179775
dtype: int64

In [41]:
pd.DataFrame(inputs[3310:3320])

            id                                          raw title
0   6428037746          Software Engineer, Model Context Protocol
1   6420017970                     Software Engineer, PC Engineer
2   6419999267                       Software Engineer, Retention
3   6421157846             Software Engineer, UI - Anthropic Labs
4   6418041238  Software Engineering Manager II, Engineering P...
5   6423413446  Software Engineering Manager II, Google Cloud ...
6   6418043340  Software Engineering Manager II, Infrastructur...
7   6419828255        Software Quality Engineering Senior Manager
8   6420613029  Solar and Building to Grid Codified Attack Sur...
9   6421769364  Solar Field Service Technician (Operations and...
10  6421841510  Solar Field Service Technician (Operations and...

In [12]:
json.loads(output)

[{'raw title': '.NET Software Developer II',
  'title name': '.NET Developer',
  'span': '.NET Software Developer II',
  'seniority': 'Mid'},
 {'raw title': 'Grocery Manager',
  'title name': 'Grocery Manager',
  'span': 'Grocery Manager',
  'seniority': 'None'},
 {'raw title': 'Licensed Clinical Therapist (General Application)',
  'title name': 'Clinical Therapist',
  'span': 'Licensed Clinical Therapist',
  'seniority': 'None'},
 {'raw title': '1st shift Digital Technician',
  'title name': 'Digital Technician',
  'span': 'Digital Technician',
  'seniority': 'None'},
 {'raw title': '1st Shift Warehouse Team Lead',
  'title name': 'Warehouse Team Lead',
  'span': 'Warehouse Team Lead',
  'seniority': 'None'},
 {'raw title': '1st Shift Warehouse Team Lead, Receiving Clerk',
  'title name': 'Warehouse Team Lead',
  'span': 'Warehouse Team Lead',
  'seniority': 'None'},
 {'raw title': '2024-25 SPED ESY Instructional Assistant/Special Education - Special Education',
  'title name': 'Instructional Assistant',
  'span': 'Instructional Assistant',
  'seniority': 'None'},
 {'raw title': '2025 - 2026 Judicial Law Clerkship with Judge David B. Gass',
  'title name': 'Judicial Law Clerk',
  'span': 'Judicial Law Clerk',
  'seniority': 'None'},
 {'raw title': '2025 - Summer Associate- Energy, Resources & Infrastructure (ERI)',
  'title name': 'Summer Associate',
  'span': 'Summer Associate',
  'seniority': 'None'},
 {'raw title': '2025 ATS Technology Development Program- Event Only',
  'title name': 'Technology Development Program',
  'span': 'Technology Development Program',
  'seniority': 'None'}]

In [3]:
for raw_title in df["Original title"][:5].values:
    output = await generate_title(raw_title)
    print(output)

Number of input tokens:  251
Number of output tokens:  50
{
    "raw title": "$21-FORKLIFT OPERATOR-2ND SHIFT",
    "title name": "Forklift Operator",
    "span": "FORKLIFT OPERATOR",
    "seniority": "None"
}
Number of input tokens:  252
Number of output tokens:  36
{
    "raw title": "Computer Technician",
    "title name": "Computer Technician",
    "span": "Computer Technician",
    "seniority": "None"
}
Number of input tokens:  250
Number of output tokens:  38
{
    "raw title": "Integration/Test Engineer",
    "title name": "Test Engineer",
    "span": "Integration/Test Engineer",
    "seniority": "None"
}
Number of input tokens:  251
Number of output tokens:  49
{
    "raw title": "(HA SME) HUMINT Analyst Subject Matter Expert ISSJ",
    "title name": "HUMINT Analyst",
    "span": "HUMINT Analyst",
    "seniority": "None"
}
Number of input tokens:  267
Number of output tokens:  51
{
    "raw title": "BUILDING MAINTENANCE MECHANIC",
    "title name": "Maintenance Mechanic",
    "span": "BUILDING MAINTENANCE MECHANIC",
    "seniority": "None"
}