In [1]:
import pandas as pd
import re
import instructor
from openai import AsyncOpenAI
import asyncio
from tqdm.asyncio import tqdm

In [2]:
aclient = instructor.patch(AsyncOpenAI())

In [41]:
model = "gpt-4o-mini"
numerical_regex = re.compile(r"^\d+[\.]?\s*")

def make_batches(titles, batch_size):
    return [titles[i:i+batch_size] for i in range(0, len(titles), batch_size)]

def rm_newlines(title):
    return re.sub(r"\n+", " ", title)

def make_input_content(titles):
    return "\n".join([f"{i+1}. "+ rm_newlines(title) for i, title in enumerate(titles)])

async def fetch_response(titles):
    content = make_input_content(titles)
    prompt = f"""You are a HR and language expert.
        You will be provided with a numerical list of job titles, and your task is to translate them into English.
        The output should be a numerical list of translated titles separated by newline."""
    messages = [
                    {
                        "role": "system",
                        "content": prompt
                    },
                    {
                        "role": "user",
                        "content": content
                    }
                ]

    try:
        response = await aclient.chat.completions.create(
            model=model,
            messages=messages
        )
        output = response.choices[0].message.content
        return output
    except Exception as e:
        print(f"Error processing input '{text}': {str(e)}")
        return None

def remove_numerical(title):
    return numerical_regex.sub("", title).strip()

def process_output_content(content):
    titles = content.split("\n")
    return [remove_numerical(title) for title in titles]

def get_titles(contents):
    titles = []
    for content in output_titles:
        if content:
            title_batch = process_output_content(content)
            if len(title_batch) == batch_size:
                titles += title_batch
            else:
                titles += [""] * batch_size
        else:
            titles += [""] * batch_size
    return titles

async def translate_titles(titles, batch_size: int=10):
    title_batches = make_batches(titles, batch_size)
    tasks = [fetch_response(titles) for titles in title_batches]
    responses = await tqdm.gather(*tasks)
    titles = get_titles(responses)
    return responses

In [42]:
df = pd.read_parquet("data/inputs/LT-1.parquet")
all_titles = df["job_title"].to_list()[:50]

In [43]:
output_titles = await translate_titles(all_titles, batch_size=5)

100%|███████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.35it/s]

In [44]:
output_titles

['1. FAST FOOD BAKER | NO EXPERIENCE? WE WILL TRAIN YOU\n2. Salesperson - Consultant\n3. Administrator of the Operations Group of the Science and Innovation Center of the Agricultural Service\n4. MANAGER OF THE CUSTOMER SERVICE DEPARTMENT (0.5 FTE) (FIXED-TERM CONTRACT)\n5. Specialist of the Dainava Division of the South Lithuania Customer Service Center',
 '1. Accountant  \n2. Senior Accountant | Option to Work Part-Time from Home  \n3. Rail Baltica Business Analyst  \n4. Expert (Finance Sector) | Public and Private Partnership Department  \n5. Tax Consultant  ',
 '1. Business Analyst  \n2. Human Resources and Office Management Manager  \n3. Accountant  \n4. Female Accountant  \n5. Chief Accountant  ',
 '1. Chief Specialist of Operational Control (Public Servant)  \n2. Accountant  \n3. Specialist in the Financial Markets Operations Group  \n4. Accountant in the Financial Service  \n5. Senior Accountant / Accountant',
 '1. Senior Accountant  \n2. Accountant (3 days)  \n3. Senior Accountant  \n4. SENIOR ACCOUNTANT | HYBRID WORK MODEL  \n5. SENIOR ACCOUNTANT | HYBRID WORK MODEL  ',
 '1. Consultant for the "RIVILE GAMA" Accounting and Business Management System  \n2. IT Engineer  \n3. Senior Accounting Specialist-Controller (for International Team)  \n4. Client Consulting Manager  \n5. Support Staff',
 '1. Cleaner  \n2. Cleaner  \n3. Call Center Quality Manager  \n4. Fast Food Baker | Experience Not Required - Training Provided  \n5. Waiters in the Conference Center | Temporary Job  ',
 '1. Office Administrator  \n2. Special Cleaning Work Employee  \n3. Information Center Manager  \n4. Remote Consulting Department Consultant in Kaunas, Utena (Fixed-Term Employment Contract)  \n5. Project Manager for Customer Experience and Quality Management Department  ',
 '1. FAST FOOD COOK | NO EXPERIENCE? WE WILL TRAIN YOU\n2. Travel Companion\n3. Youth Worker - Case Coordinator for the "Connections" Project\n4. Customer Service Manager (e-commerce)\n5. Strategy Director',
 '1. Risk Management Specialist  \n2. Science Coordinator  \n3. Internal Auditor  \n4. Senior Project Manager I Local Action Group Projects Department  \n5. Project Manager I Local Action Group Projects Department  ']

In [51]:
output_titles = [None, None] + output_titles

In [21]:
df = pd.read_parquet("data/inputs/LT-1.parquet")
titles = df["job_title"].to_list()[:10]
title_batchs = make_batches(titles, batch_size=2)

### Test module for different languages

In [7]:
import pandas as pd
from translate_titles import translate_titles

In [10]:
df_lt = pd.read_parquet("data/inputs/LT-1.parquet")
titles_lt = df_lt["job_title"].to_list()[:1000]

In [14]:
titles_en = await translate_titles(titles=titles, batch_size=50)

100%|███████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.21s/it]

In [21]:
pd.DataFrame({
    "title": titles,
    "title_en": title_en
})

                                                 title                                           title_en
0    GREITO MAISTO KEPĖJA (-AS) | NETURI PATIRTIES?...  FAST FOOD BAKER | NO EXPERIENCE? WE WILL TRAIN...
1                      Pardavėja(-s) - konsultantė(-as                           Salesperson - Consultant
2    Ūkio tarnybos Mokslo ir inovacijų centro ekspl...  Administrator of the Operations Group at the S...
3    KLIENTŲ APTARNAVIMO SKYRIAUS VADYBININKĖ (-AS)...  CUSTOMER SERVICE DEPARTMENT MANAGER (0.5 FTE) ...
4    Pietų Lietuvos Klientų aptarnavimo centro Dain...  Specialist at the Dainava Division of the Sout...
..                                                 ...                                                ...
995  Tarptautinių mokestinės informacijos mainų spe...  International Tax Information Exchange Specialist
996                               Vyr. teisininkas (-ė                                      Senior Lawyer
997                                   Teisininkė /- as                                             Lawyer
998     SPECIALISTAI (-ĖS) TEISINIŲ DOKUMENTŲ RENGIMUI         SPECIALISTS FOR LEGAL DOCUMENT PREPARATION
999  Projektų vadovas (-ė) I Europos infrastruktūro...  Project Manager in the European Infrastructure...

[1000 rows x 2 columns]

In [22]:
df_bd = pd.read_parquet("data/inputs/BD-1.parquet")
titles_bd = df_bd["job_title"].to_list()[:1000]

In [23]:
titles_en = await translate_titles(titles=titles_bd, batch_size=50)

100%|███████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.77it/s]

In [24]:
pd.DataFrame({
    "title": titles_bd,
    "title_en": titles_en
})

                            title                      title_en
0                         প্রভাষক                      Lecturer
1          হিফয শিক্ষক ( আবাসিক )   Hafiz Teacher (Residential)
2                      ইঞ্জিনিয়ার                      Engineer
3                           নায়েব                        Deputy
4                      অফিস সহায়ক              Office Assistant
..                            ...                           ...
995  Assistant Production Manager  Assistant Production Manager
996            Production Manager            Production Manager
997                রুম সার্ভিস বয়              Room Service Boy
998                        Waiter                        Waiter
999                    বিউটিশিয়ান                    Beautician

[1000 rows x 2 columns]

In [32]:
pd.set_option('display.max_rows', 500)

In [27]:
df_id = pd.read_parquet("data/inputs/ID-1.parquet")
titles_id = df_id["job_title"].to_list()[:1000]

In [28]:
titles_en = await translate_titles(titles=titles_id, batch_size=50)

100%|███████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:40<00:00,  2.00s/it]

In [33]:
pd.DataFrame({
    "title": titles_id,
    "title_en": titles_en
})[:100]

                                                title                                           title_en
0         Micro Sales Officer - Surabaya & Sekitarnya  Micro Sales Officer - Surabaya & Surrounding A...
1              Hub Lead - Shopee Xpress (Banjarmasin)             Hub Lead - Shopee Xpress (Banjarmasin)
2                                               Sales                                              Sales
3                                         Sales Admin                                        Sales Admin
4                             Nail Terapis / Nail Art                          Nail Therapist / Nail Art
5   Sales B2B / Commersial / Industri / Project (U...  B2B / Commercial / Industrial / Project Sales ...
6                                              Driver                                             Driver
7                                             Mekanik                                           Mechanic
8                    Lash Terapis / Eyelash Extension                 Lash Therapist / Eyelash Extension
9                                        Team Drafter                                       Team Drafter
10                                           Reporter                                           Reporter
11                                             Driver                                             Driver
12                                            Finance                                            Finance
13                                            Drafter                                            Drafter
14                                        Teknisi UPS                                     UPS Technician
15                                        Staff Admin                                        Admin Staff
16                                  SALESMAN - MALANG                                  SALESMAN - MALANG
17                                           Surveyor                                           Surveyor
18                    Sales Modern Trade Cabang medan                    Modern Trade Sales Branch Medan
19                                        Cook Helper                                        Cook Helper
20                                         Sales Toko                                        Store Sales
21   Senior Sales Representatives - Jakarta/Tangerang   Senior Sales Representatives - Jakarta/Tangerang
22                        Field Collector Area Manado                        Field Collector Area Manado
23                Staff Administrasi & Packing Gudang           Warehouse Administration & Packing Staff
24                                      Sales Cirebon                                      Sales Cirebon
25       Field Collector Penempatan Malang & Pasuruan        Field Collector Placement Malang & Pasuruan
26                               Admin Toko Bahan Kue                                  Pastry Shop Admin
27                                  Cleaning Services                                  Cleaning Services
28                                         Admin Staf                                        Admin Staff
29                                   Kepala Kendaraan                                       Vehicle Head
30                                    SALES MARKETING                                    SALES MARKETING
31                                             DRIVER                                             DRIVER
32  Operational Branch Support Staff (Pontianak Area)  Operational Branch Support Staff (Pontianak Area)
33                     Staf Administrasi dan Akutansi                Administration and Accounting Staff
34           Sales Project CCTV Area Serang & Cilegon           CCTV Project Sales Area Serang & Cilegon
35                               BUILDING MAINTENANCE                               BUILDING MAINTENANCE
36  Marketing Verification Officer (JS - MVO) Sido...  Marketing Verification Officer (JS - MVO) Sido...
37                                              SALES                                              SALES
38            Retail Sales Representative (Gorontalo)            Retail Sales Representative (Gorontalo)
39                                        TEKNISI EDC                                     EDC Technician
40                                   ACCOUNTING STAFF                                   ACCOUNTING STAFF
41                                  Flutter Developer                                  Flutter Developer
42                                  Admin Online Shop                                  Online Shop Admin
43              Sales Assistant (Bali dan Yogyakarta)              Sales Assistant (Bali and Yogyakarta)
44                                         PROGRAMMER                                         PROGRAMMER
45                                      Programmer C#                                      C# Programmer
46                                      ASISTEN BIDAN                                  MIDWIFE ASSISTANT
47                          Sales Associate (Cilegon)                          Sales Associate (Cilegon)
48                            Sales Associate (Jambi)                            Sales Associate (Jambi)
49                                        Kurir Kerry                                      Kerry Courier
50                       Rider Driver area Kalimantan                       Rider Driver area Kalimantan
51                               Sales Representative                               Sales Representative
52                    Field Collection Area Palembang                    Field Collection Area Palembang
53                        Field Collection Area Ambon                        Field Collection Area Ambon
54                Field Collection Area Jakarta Timur                 Field Collection Area East Jakarta
55                    Sales Associate (Kepuluan Riau)                     Sales Associate (Riau Islands)
56                           Sales Associate (Kediri)                           Sales Associate (Kediri)
57                   Field Collection (Kepulauan Riau                    Field Collection (Riau Islands)
58                   Field Collection Area Majalengka                   Field Collection Area Majalengka
59  Field Asset Management 1-90 Motorcycle Branch ...  Field Asset Management 1-90 Motorcycle Branch ...
60                           Operational Housekeeping                           Operational Housekeeping
61                          Sales Associate (Lampung)                          Sales Associate (Lampung)
62                Sales Associate (Tangerang Selatan)                  Sales Associate (South Tangerang)
63                   Field Collection Area Payakumbuh                   Field Collection Area Payakumbuh
64                            Sales Associate (Medan)                            Sales Associate (Medan)
65                             Sales Associate (Riau)                             Sales Associate (Riau)
66                    Field Collection Area Pekanbaru                    Field Collection Area Pekanbaru
67                             Database Administrator                             Database Administrator
68                Administrasi Front Office Pamekasan              Front Office Administration Pamekasan
69                                           Security                                           Security
70                                              BIDAN                                            MIDWIFE
71                      ANDROID IOS DEVELOPER (MEDAN)                      ANDROID IOS DEVELOPER (MEDAN)
72                     SECRETARY SEKRETARIS MARKETING                                SECRETARY MARKETING
73                                 Operations Manager                                 Operations Manager
74                                    Service Manager                                    Service Manager
75                                    Sales Marketing                                    Sales Marketing
76                                    JAVA PROGRAMMER                                    JAVA PROGRAMMER
77                                  GOLANG PROGRAMMER                                  GOLANG PROGRAMMER
78     Showroom Manager (Furniture & Kitchen Product)     Showroom Manager (Furniture & Kitchen Product)
79              MT Sales Manager (Jawa Timur Selatan)                      MT Sales Manager (South Java)
80                                           Staff IT                                           IT Staff
81                      IT Trainer & Customer Support                      IT Trainer & Customer Support
82                                       Team Support                                       Team Support
83                   Backbone & DC Operation Engineer                   Backbone & DC Operation Engineer
84           Sr. Telecommunication Engineer (Project)           Sr. Telecommunication Engineer (Project)
85                        IT Infrastructure & Support                        IT Infrastructure & Support
86                                     Branch Manager                                     Branch Manager
87                                    Brand Executive                                    Brand Executive
88                                     Branch Manager                                     Branch Manager
89                                   Sales Supervisor                                   Sales Supervisor
90  Branch Manager Mobil (Sales & Lease Back) Wila...  Branch Manager Mobile (Sales & Lease Back) Den...
91                                      Spv Transport                               Transport Supervisor
92                                         Guru Kelas                                      Class Teacher
93                                    PROJECT MANAGER                                    PROJECT MANAGER
94                                        IT SAP ABAP                                        IT SAP ABAP
95                                     Teknisi Gadget                                  Gadget Technician
96          IT Business System Project Analysis Staff          IT Business System Project Analysis Staff
97                              MARKETING PROJECT/ IT                              MARKETING PROJECT/ IT
98                                    Project Manager                                    Project Manager
99                                           IT STAFF                                           IT STAFF

In [30]:
titles_id

['Micro Sales Officer - Surabaya & Sekitarnya',
 'Hub Lead - Shopee Xpress (Banjarmasin)',
 'Sales',
 'Sales Admin',
 'Nail Terapis / Nail Art',
 'Sales B2B / Commersial / Industri / Project (URGENT)',
 'Driver',
 'Mekanik',
 'Lash Terapis / Eyelash Extension',
 'Team Drafter',
 'Reporter',
 'Driver',
 'Finance',
 'Drafter',
 'Teknisi UPS',
 'Staff Admin',
 'SALESMAN - MALANG',
 'Surveyor',
 'Sales Modern Trade Cabang medan',
 'Cook Helper',
 'Sales Toko',
 'Senior Sales Representatives - Jakarta/Tangerang',
 'Field Collector Area Manado',
 'Staff Administrasi & Packing Gudang',
 'Sales Cirebon',
 'Field Collector Penempatan Malang & Pasuruan',
 'Admin Toko Bahan Kue',
 'Cleaning Services',
 'Admin Staf',
 'Kepala Kendaraan',
 'SALES MARKETING',
 'DRIVER',
 'Operational Branch Support Staff (Pontianak Area)',
 'Staf Administrasi dan Akutansi',
 'Sales Project CCTV Area Serang & Cilegon',
 'BUILDING MAINTENANCE',
 'Marketing Verification Officer (JS - MVO) Sidoarjo',
 'SALES',
 'Retail Sales Representative (Gorontalo)',
 'TEKNISI EDC',
 'ACCOUNTING STAFF',
 'Flutter Developer',
 'Admin Online Shop',
 'Sales Assistant (Bali dan Yogyakarta)',
 'PROGRAMMER',
 'Programmer C#',
 'ASISTEN BIDAN',
 'Sales Associate (Cilegon)',
 'Sales Associate (Jambi)',
 'Kurir Kerry',
 'Rider Driver area Kalimantan',
 'Sales Representative',
 'Field Collection Area Palembang',
 'Field Collection Area Ambon',
 'Field Collection Area Jakarta Timur',
 'Sales Associate (Kepuluan Riau)',
 'Sales Associate (Kediri)',
 'Field Collection (Kepulauan Riau',
 'Field Collection Area Majalengka',
 'Field Asset Management 1-90 Motorcycle Branch Minahasa Selatan',
 'Operational Housekeeping',
 'Sales Associate (Lampung)',
 'Sales Associate (Tangerang Selatan)',
 'Field Collection Area Payakumbuh',
 'Sales Associate (Medan)',
 'Sales Associate (Riau)',
 'Field Collection Area Pekanbaru',
 'Database Administrator',
 'Administrasi Front Office Pamekasan',
 'Security',
 'BIDAN',
 'ANDROID IOS DEVELOPER (MEDAN)',
 'SECRETARY SEKRETARIS MARKETING',
 'Operations Manager',
 'Service Manager',
 'Sales Marketing',
 'JAVA PROGRAMMER',
 'GOLANG PROGRAMMER',
 'Showroom Manager (Furniture & Kitchen Product)',
 'MT Sales Manager (Jawa Timur Selatan)',
 'Staff IT',
 'IT Trainer & Customer Support',
 'Team Support',
 'Backbone & DC Operation Engineer',
 'Sr. Telecommunication Engineer (Project)',
 'IT Infrastructure & Support',
 'Branch Manager',
 'Brand Executive',
 'Branch Manager',
 'Sales Supervisor',
 'Branch Manager Mobil (Sales & Lease Back) Wilayah Denpasar',
 'Spv Transport',
 'Guru Kelas',
 'PROJECT MANAGER',
 'IT SAP ABAP',
 'Teknisi Gadget',
 'IT Business System Project Analysis Staff',
 'MARKETING PROJECT/ IT',
 'Project Manager',
 'IT STAFF',
 'IT PRODUCT SUPPORT / PRESALES SUPPORT',
 'IT Programmer',
 'PreSales',
 'Mobile Developer',
 'Legal Generalist',
 'QUALITY ASSURANCE',
 'Lead Content Writer',
 'IT MIS',
 'IT Product Manager',
 'Administrasi Gudang Warehouse Pangkal Pinang',
 'Administrasi Umum Morowali',
 'Administrasi Front Office Aceh Utara',
 'Medical Sales Representative (South Bali)',
 'PROGRAMMER',
 'Sales Executive',
 'MT Business Relationship Officer - Surabaya',
 'SALES Development EXECUTIVE',
 'RELATIONSHIP MANAGER',
 'ACCOUNT MANAGER',
 'Retail Sales Executive',
 'Client Advisor - Sales',
 'Sales',
 'Sales Project Executive',
 'Sales',
 'Business Acquisition',
 'ACCOUNT EXECUTIVE',
 'Relationship Manager (RM)',
 'Key Account Manager',
 'Relationship Manager KC Balikpapan',
 'Sales Executive',
 'Micro Sales Officer (Jabodetabek)',
 'Funding Head',
 'AREA SALES MANAGER',
 'Head of Channel Development',
 'Sales Executive',
 'Sales Manager',
 'SALES REPRESENTATIVE',
 'Senior Account Manager (Area Palembang)',
 'SALES EXECUTIVE',
 'Business Development Analyst',
 'SALES MANAGER FLEET/END USER',
 'Sales Manager',
 'Sales & Marketing Maklon Kosmetik',
 'SALES EXECUTIVE (CIKARANG)',
 'Account Executive',
 'BUSINESS DEVELOPMENT',
 'Sales Corporate Caption',
 'Sales Marketing',
 'SALES',
 'Branch Manager (Jawa Timur)',
 'SALES MARKETING',
 'Trade Marketing Special Channel',
 'Sales Executive JABODETABEK',
 'Sales Marketing Executive',
 'SALES EXECUTIVE (TANGERANG)',
 'SALES EXECUTIVE',
 'Surveyor Motor - Account Verificator Branch Rantau Prapat',
 'Purchasing Staff',
 'KOORDINATOR AREA',
 'Staff Purchasing',
 'BARISTA',
 'Management Trainee',
 'Waiters',
 'Staff Administrasi (Jakarta)',
 'Staff Hrd',
 'SHOPKEEPER',
 'Offline Promotor - Tangerang',
 'MANAGER RESTORAN',
 'Staff Karyawan',
 'Crew Stand Minuman',
 'Staf Resto',
 'Pegawai Toko',
 'PENJAGA STAND',
 'Pelayan Cafe',
 'STAFF PERPUSTAKAAN',
 'Staff Administrasi',
 'Host Live Streaming',
 'TAX STAFF',
 'Captain Floor',
 'CASHIER CAPTAIN - OSTERIA GIA PIK',
 'BARISTA - JABODETABEK',
 'Penjaga Stand Minuman',
 'Customer Service',
 'Waitress',
 'Konsultan Herbal',
 'Offline Promotor - Depok',
 'Staff HRD',
 'Barista',
 'Barberman',
 'Pendidik',
 'Kitchen Crew',
 'Perawat',
 'COOK - OSTERIA GIA PIK',
 'Staff outlet juice bar Kota Kasablanka',
 'PENJAHIT KONVEKSI',
 'Tukang Masak',
 'Assistant Sales Staff (YL Samarinda)',
 'BARISTA',
 'Kitchen Crew',
 'Crew Outlet',
 'Kitchen crew',
 'General Affair Staff',
 'GRO (Guest Relation Officer)',
 'Customer Service dan Teller',
 'Assistant Store Manager (ASM) Makassar',
 'Staff Kitchen',
 'Sales & Marketing - Balikpapan',
 'JAGA STAND MAKANAN',
 'Merchant & Customer Acquisition',
 'Staff Administrasi',
 'Salesman Project (Oli Industri & Cat)',
 'Karyawan',
 'Cook',
 'Karyawan Resto',
 'Karyawan',
 'Kitchen Crew / Kitchen Helper',
 'Waiter/Waitress',
 'Staff Gudang',
 'Waiter/Waitress',
 'staff laundry',
 'Direct Sales Marketing Firstmedia Bandung',
 'sales engineering',
 'Executive Sales',
 'Relationship Manager Mortgage',
 'Kitchen',
 'Front of House',
 'Karyawan Store',
 'Guru Bahasa Jepang',
 'Housekeeping',
 'Staff Akuntansi',
 'Karyawan Counter HP',
 'Chef',
 'Karyawan Outlet',
 'Host Live Streaming',
 'Waiters / Waitress',
 'Office Boy',
 'COOK/KOKI - Chinese Restaurant',
 'Staff Administrasi dan Customer Service',
 'SALES ACQUISITION',
 'Pramuiaga Toko',
 'Hotel manager',
 'Store Staff (Jambi)',
 'Kasir',
 'Karyawan/karyawati',
 'BARTENDER',
 'Cook helper',
 'Staff toko',
 'Kitchen',
 'Waiter/Waitress',
 'Waiter & waitres',
 'Assisten Direktur',
 'Karyawati Kasir Toko Minimarket',
 'SPG',
 'BARISTA',
 'Staff karyawan',
 'Cook Helper',
 'Collection Staff',
 'Store Staff (Jambi)',
 'Store Staff (Cibinong)',
 'Store Staff (Fashion Retail)',
 'Field Collection Area Medan',
 'PRAMUNIAGA',
 'Store Staff (Cibinong)',
 'Operational Housekeeping',
 'Cook',
 'KASIR',
 'CREW STAND',
 'Leader Kasir',
 'Supervisor Restaurant',
 'Waiters / Waitress',
 'RECEPTIONIST',
 'Staff Penagihan / Kolektor',
 'Store Crew',
 'Sales',
 'HOST LIVE STREAMING',
 'Front Office Manager',
 'Waiters / Pramusaji',
 'Store Manager (Tangerang)',
 'Penjaga Stand',
 'STORE SUPERVISOR - RESTAURANT JAMBI',
 'Karyawan Toko',
 'GURU',
 'Crew Outlet',
 'FRONLINER',
 'Staff Administrasi Yayasan',
 'KARYAWAN TOKO',
 'Purchasing Staff',
 'Pelaksana Underwriting',
 'Customer Assistant',
 'Guru Calistung',
 'Trainer Koki',
 'Receptionist',
 'Barista',
 'Waiters / Waitress',
 'Barista',
 'Crew store',
 'Offline Promotor - DKI Jakarta',
 'Outlet Crew',
 'Kasir',
 'Boga Group Walk In Interview Jambi',
 'CASHIER',
 'STAFF ADMINISTRASI EKSPEDISI',
 'Barista',
 'COOK/KOKI',
 'Store Staff (Fashion Retail)',
 'Host Live Streaming Tiktok',
 'Management Trainee Kepala Administrasi',
 'Audit Staff',
 'Medical Representative DUMAI',
 'Maintenance mesin bubut manual dan CNC',
 'Admin',
 'Junior Supervisor / Pengawas Lapangan (JS)',
 'Accounting Staff',
 'Pegawai toko',
 'Credit Marketing Officer (CMO) Jawa Timur',
 'Internal Audit Staff',
 'Internal Audit Staff',
 'Host Live Streaming',
 'Warehouse Staff - Surabaya',
 'WAITERS',
 'STAF AKADEMIK BAHASA',
 'Barista',
 'Guru',
 'Dokter Umum THC Madiun',
 'Cook',
 'Barista',
 'Expert Teacher for History',
 'Tenaga Kerja Cuci Mobil',
 'Manager Sales Principal Agency Property',
 'Marketing Otomotif',
 'ADMIN PASTRY',
 'Tentor TPA/Skolastik',
 'Associate PT. BRI Asuransi Indonesia',
 'STAFF ACCOUNTING FINANCE',
 'SPG - SPB OUTLET',
 'General Affair',
 'COOK/ MEMASAK',
 'Pembuat Bunga',
 'STAFF CARPOOL',
 'SPG',
 'Sales Perbankan (pensiunan)',
 'SPG',
 'Karyawati Counter',
 'Casier/kasir/runner',
 'Karyawati Laundry',
 'LOWONGAN KERJA TERBARU 2023 | LOWONGAN KERJA DI JABODETABEK SEGERA',
 'Waitres',
 'Store Manager',
 'Front Office/ Trainee',
 'DW HOUSEKEEPING',
 'Staff Gudang',
 'Waiter dan Kasir CLG',
 'Assistant Store Manager',
 'Cook Helper',
 'LOWONGAN KERJA TERBARU 2023 | LOWONGAN KERJA DI TANGERANG SEGERA',
 'BARISTA',
 'Pramuniaga Toko',
 'Apoteker Pendamping',
 'Sales',
 'Administrasi Keuangan Kantor Tanjung Pinang',
 'Administrasi Data Support Blora',
 'GADGET ADVISOR SINGARAJA',
 'Hair Stylist',
 'Vaporista',
 'Cook Team',
 'Steward (Daily Worker)',
 'Implementation Specialist',
 'Security',
 'Field Asset Management 1-90 Car - Branch Tomohon',
 'Pharma Sales Representative',
 'Sales Executive',
 'TENAGA TEKNIS KEFARMASIAN',
 'DOKTER UMUM',
 'STAFF ADMINISTRATOR',
 'Trade Marketing Internship',
 'Barista',
 'Admin ( Depok )',
 'Legal Staff',
 'Admin Part Order',
 'Admin Online Shop',
 'Host Live Tiktok',
 'Telemarketing Staff',
 'GURU BK',
 'Apoteker',
 'SENIOR HAIRSTYLIST',
 'Guru TKJ',
 'CAMERAMAN',
 'Medical Representative Pekanbaru',
 'HCBP Staff',
 'Learning Support Staff',
 'JUNIOR ARSITEK',
 'Crew Cafe',
 'Business Development',
 'Waiter',
 'Auditor LSSM',
 'Crew Outlet',
 'Perawat',
 'Sales',
 'Staff CORNER Laundry',
 'Chef Frozen Food',
 'Pegawai toko',
 'IT Sales Representative',
 'Pharma Sales Representative (Denpasar)',
 'Clerk Sales Administration',
 'TUTOR',
 'Sales Canvas',
 'Finance Staff',
 'Admin Store',
 'Accounting Staff',
 'Recruitment Staff (Temporary)',
 'GURU TKJ',
 'Sales Executive',
 'House Keeping',
 'Staff Administrasi',
 'DOKTER ESTETIKA',
 'Human Resources Intern (JS - HR INT)',
 'CHAPTER',
 'Waiters/waitress',
 'Pengajar Anak Berkebutuhan Khusus (Terapis)',
 'Crew Outlet (Full Time & Part Time)',
 'Terapis Nailart (Singgasana Pradana & holis regency)',
 'Call Center Internship',
 'Data Analyst Internship',
 'Kurir (Mitra)',
 'Barista',
 'Lowongan Copywriter & Staff Admin di HiSpeedFlow Yogyakarta',
 'Bank Kalsel Management Associate Program',
 'Marketing Agency (Motor Product) - Branch Rembang',
 'Account Officer - Malang',
 'SPG dan SPB',
 'SPG dan SPB',
 'SPG dan SPB',
 'SPG dan SPB',
 'Frontliner',
 'Desain Grafis',
 'Design Grafis',
 'Coorporate Advertising',
 'Marketing',
 'Social Media Officer',
 'Commercial Officer',
 'THERAPIST SPA',
 'Marketing UMKM',
 'Kepala Marketing',
 'Customer Marketing Executive (Surveyor) - Branch Luwu Timur',
 'Desain Grafis',
 'MARKETING ADMINISTRATION STAFF',
 'Staf Resto',
 'DESAIN GRAFIS',
 'SOCIAL MEDIA & MARKETPLACE SPECIALIST',
 'Penulis (Content Planing)',
 'Marketing Staff',
 'Account Executive (Marketing)',
 'Marketing Officer Domisili Bogor',
 'Graphic Designer Illustrator',
 'Businees Development (Marketing & Sales Specialist)',
 'Karyawan Mini Market',
 'Marketing Officer (Domisili Denpasar)',
 'Talent Video Tiktok (WFH)',
 'CONTENT CREATOR',
 'SCRIPT WRITTER',
 'MARKETING PROJECT',
 'Live Streamer',
 'Multimedia Designer',
 'Marketing',
 'SOCIAL MEDIA & MARKETPLACE SPECIALIST',
 'Design Grafis',
 'Marketing Officer Domisili Samarinda',
 'Host Live Streaming (Fashion) Part-time / Full-time',
 'Marketing Officer Domisili Bukit Tinggi',
 'YOUTUBE VIDEO EDITOR',
 'MARKETING STAFF',
 'Assistant Manager Visual Merchandise',
 'GRAPHIC DESIGNER',
 'ADMIN MEDIA SOSIAL',
 'SHORT VIDEO PROJECT LEADER',
 'Digital Marketing',
 'Marketing Officer Domisili Gorontalo',
 'HOST LIVE STREAMING ( TIKTOK )',
 'Marketing Manager',
 'Content Planner',
 'MARKETING EXECUTIVE',
 'Host Live Streaming',
 'DESAINER GRAFIS',
 'Manager Bisnis Industri Olahraga (Club Bola)',
 'DeskPrint / Design Grafis',
 'MARKETING',
 'Designer Grafis',
 'DIGITAL MARKETING',
 'Marketing Officer (Domisili Manokwari)',
 'Content Creator',
 'Marketing Taman Edukasi dan Kuliner',
 'Marketing Officer (Domisili Tasikmalaya)',
 'Senior Marketing Staff',
 'Marketing Officer Domisili Padang',
 'DIGITAL MARKETING (Online Marketing E-Commerce dan Sosial Media)',
 'Marketing Manager',
 'Marketing Officer Domisili Pontianak',
 'Marketing Officer Domisili Ambon',
 'Ass.Brand Manager',
 'MARKETING PROPERTY',
 'Marketing & Verification Officer (JS - MVO) Probolinggo',
 'SALES OPERASIONAL',
 'Marketing Project',
 'Social Media Marketing Manager',
 'HOST LIVE INSTAGRAM (FREELANCE DAN INHOUSE)',
 'Marketing Head Solo',
 'Shopkeeper',
 'Digital Marketing Staff',
 'Crew Dhiva Cosmetics',
 'Content Creator',
 'Marketing Verification Officer (JS - MVO) Pamekasan',
 'TALENT',
 'Brand Designer',
 'DESIGN GRAFIS',
 'Marketing Officer (Domisili Cikarang)',
 'Marketing Verification Officer (JS - MVO) Selong NTB',
 'MANAGER ARTIS INFLUENCER',
 'Marketing Property',
 'Content Creator',
 'Marketing Officer Domisili Singkawang',
 'Staf Marketing',
 'Affiliate Digital Marketing',
 'Digital Marketing',
 'Marketing / Pemasaran',
 'Credit Marketing Officer (CMO) - Depok',
 'Staff Design',
 'Admin Support Demak',
 'Administrasi Data Support Pasuruan',
 'Administrasi Gudang Klungkung',
 'Administrasi Gudang Palangka Raya',
 'Staff Quality Control Garut',
 'Quality Inspector',
 'Cook',
 'Lowongan kerja CREW OUTLET Bebek Goreng H. Slamet (Asli) area Bogor',
 'Lowongan kerja Administrasi Staff Ailin Kosmetik area BOGOR',
 'DRAFTER',
 'Promotor Transmart Yasmin Bogor',
 'Administrasi Data Gudang Warehouse Lombok Timur',
 'Lowongan Kerja Admin Gudang di PT Harmet Setia Cemerlang Sukoharjo',
 'Loker Bank Nomor 1 di Indonesia',
 'Loker Graphic Designer di Area 55 Studio Jogja',
 'Lowongan Pekerjaan Sales Lulusan SMA Sederajat di Perusahaan Kerupuk Semarang',
 'Loker Field Collection dan Credit Marketing Officer PT Valdo Sumber Daya\nMandiri Penempatan Solo Baru',
 'Lowongan Kerja Pimpinan Cabang Dealer HINO Jogja PT Mitra Pratama Mobilindo',
 'Lowongan Kerja Marketing di PT BPR Sindu Adi Sleman',
 'Loker Jogja di di PT Sekarnusa Kreasi Indonesia Bulan Januari 2023',
 'Loker Tukang Bubut, Teknik Mesin, Staff Lab Penempatan Boja di PT Raberindo\nPratama',
 'Lowongan Kerja SPG, Kepala Toko dan Marketing Toko Roti Kobayashi di Jogja',
 'Lowongan Pekerjaan Sopir Pribadi dan Kasir di CV Accu SOS Semarang',
 'Lowongan Kerja Pemasaran dan Sales Call di PT Nine Stars Group Semarang',
 'Lowongan Kerja SPG Tea Shop Penempatan di Solo Grand Mall, Solo Square,\nHartono Mall, Solo Paragon Mall',
 'Lowongan Kerja Finance Admin Lulusan SMA di Nagita Transport Kartasura',
 'Gratis! USB Job Fair 2023 di Universitas Setia Budi Surakarta Tanggal 24- 25\nJanuari 2023',
 'Lowongan Kerja Desain Grafis di PT Intrafood Singabera Indonesia Sukoharjo',
 'Lowongan Kerja Karyawan untuk Home Industri Snack di Sukoharjo',
 'Lowongan Kerja Supervisor Cetak Semarang di PT Muliaform Grafido',
 'Lowongan Kerja di Yana Beauty Salon Solo Bulan Januari 2023',
 'Lowongan Kerja Swamitra Solo Raya Account Officer, Credit Support dan\nOperasional',
 'Lowongan Kerja Semarang Sales Direct Selling dan Salesman di PT Sekarnusa\nKreasi Indonesia',
 'Loker Semarang Staff Promosi, SPV Lapangan dan Team Leader di PT Win Abadi\nSejahtera',
 'Lowongan Pekerjaan PT Intrafood Singabera Indonesia Sukoharjo Lulusan SMA SMK',
 'Lowongan Koordinator Kebun Tanaman & Buah Penempatan di Karangpandan\nKaranganyar',
 'Loker Marketing Property di Zeline Residence Solo Raya',
 'Lowongan Pekerjaan Insurance Advisor Penempatan Solo Raya di PT Sun Life\nFinancial Indonesia',
 'Lowongan Pekerjaan Junior Content Creator Solo Raya di Gemar Kulineran',
 'Lowongan Hairdresser dan Beauty Therapist di Kyra Beauty Studio Kartasura',
 'Lowongan Kerja Kasir dan Pramuniaga di Satelit 99 Mesintronik Solo',
 'Loker Solo Raya Staff UI - UX Apps, Back End Engineer, Digital Marketing di PT\nAscarya Global Suplai',
 'Lowongan Kerja Driver Penempatan Gentan, Sukoharjo di Humitrap Indonesia',
 'Lowongan Kerja Marketing Online Shop, Admin Online Shop, Distributor di Solo\nRaya',
 'Loker Marketing Distribusi & Admin Marketplace Part Time / Full Time di Area\nSolo dan Sekitarnya',
 'Supir Pribadi',
 'Operator Quality Control (Garment)',
 'Digital Marketing Specialist',
 'Mekanik',
 'Sales Engineer',
 'Lowongan Kerja Januari 2023 di PT Dermavous Essensia Utama Sukoharjo',
 'Kepala Pabrik - Industri Roti',
 'GURU',
 'Staff PPIC (Operator Produksi)',
 'Pegawai Produksi',
 'STAFF PRODUKSI',
 'Management Trainee - Transportation, Production, & Reparation (Traction)',
 'Research Development (RnD) Staff',
 'Translator Mandarin Indonesia Pabrik',
 'Tukang Las Mesin',
 'Quality Control dan Checker',
 'Supervisor Produksi filling dan packaging Liquid dan Cream',
 'Penejermah Bahasa Mandarin',
 'Analis QC Finish Product',
 'Kepala Produksi Rota-SS',
 'Purchasing Staff (Teknik)',
 'Staf produksi',
 'MANDARIN TRANSLATOR',
 'Capster',
 'Staff PPIC (2 Orang)',
 'DRAFTER INTERIOR',
 'OPERATOR',
 'PRODUKSI BAKERY',
 'Bagian Operasional',
 'Kepala Workshop',
 'OPERATOR WORKSHOP',
 'Operator Jahit',
 'GENERAL MANAGER',
 'CASHIER',
 'CREATIVE TEAM',
 'Internal Audit Supervisor',
 'ASISTEN TRANSPORT',
 'PRODUCTION CONTROL STAFF',
 'Interior Designer',
 'Produksi',
 'Field Service Operator',
 'Guru Bahasa Indonesia',
 'TRANSLATOR MANDARIN',
 'Sales Kitchen Designer (Surabaya)',
 'Grafis Designer',
 'Supervisor Produksi',
 'CIVIL ENGINEERING STAFF',
 'INTERNSHIP - TALENT SOURCING',
 'STAFF PRODUKSI',
 'KEPALA PLYWOOD',
 'ACCOUNT EXECUTIVE - AE',
 'Penerjemah Mandarin',
 'Kepala PPIC',
 'PRODUCTION MANAGER',
 'Staf Produksi',
 'Business Development Manager Farmasi',
 'OPERATOR BUBUT MILLING CNC WIRECUT',
 'Fullstack Developer',
 'E Commerce Specialist',
 'Tim Produksi',
 'Drafter Interior',
 'Karyawan Produksi Kue',
 'Deskprint Staff (Computer Grafis Operator) / Design Staff',
 'Graphic Designer',
 'PHOTOGRAPHER FASHION',
 'HOST LIVE TIKTOK / KONTEN KREATOR',
 '2D Artist',
 'Digital Marketing',
 'Lowongan Kerja Perusahaan Fashion di Jogja Januari 2023',
 'Admin Produksi',
 'Operator Wheel Loader',
 'Staff Accounting (General Ledger)',
 'Manager Produksi',
 'QC Manager',
 'Staff Checker (Cost Control)',
 'Lowongan Kerja HR Generalist Full Time di Scholars Solo',
 'Lowongan Kerja Host Live Marketplace di Rown Division Solo',
 'Loker Solo HRD, Administrasi dan Mekanik di PT Anugrah Vindo Abadi',
 'Loker Solo Raya Januari 2023 di PT Wirasindo Santakarya',
 'OPERATOR GBT AND TOOLS',
 'Administrasi Gudang Warehouse Pemalang',
 'Operator Produksi',
 'Staff Operator Produksi Asahan',
 'Operator Produksi',
 'Operator Produksi',
 'Operator Produksi',
 'Operator Produksi',
 'Administrasi Front Office Asahan',
 'Staff Kantor Area Paniai',
 'Cleaning Service dan Kebersihan CLG',
 'Cleaning Service',
 'Legal Staff Jaksel',
 'OB Office Boy dan Staff Gudang',
 'Administrasi',
 'Administrasi Gudang Ngawi',
 'Administrasi Gudang Sumbawa',
 'Administrasi Data Gudang Warehouse Kendari',
 'Cleaning Service',
 'Administrasi Support Surabaya',
 'Administrasi Gudang Binjai',
 'OB Office Boy',
 'Cleaning Service',
 'Data Entry',
 'Staff Administrasi Support Padangsidempuan',
 'Administrasi JKTS',
 'OB Office Boy',
 'Administrasi',
 'Admin Support Madiun',
 'Administrasi Gudang Banjarnegara',
 'Driver Operasional JKTB',
 'Administrasi Gudang Siak',
 'Staff Administrasi Support Kotawaringin Timur',
 'Receptionist Kantor Purwakarta',
 'Administrasi Data Gudang Warehouse Lumajang',
 'Administrasi Data Gudang Warehouse Pasuruan',
 'Administrasi Data Gudang Warehouse Banjarnegara',
 'Driver Operasional DPK',
 'Karyawan Operator Produksi CJR',
 'Staff Admin Jakarta Selatan',
 'OB Office Boy dan Staff Gudang',
 'OB Office Boy',
 'Admin Support Probolinggo',
 'Administrasi Gudang Kendal',