In [52]:
import pandas as pd
from tqdm import tqdm
from job_agents.generate_titles import check_title

In [58]:
df_check = pd.read_excel("data/Heathrow Rest of Functions Mapping Request_Complex case_for Ruihao.xlsx", sheet_name=1)

In [59]:
df_check

,raw title,JOB DESCRIPTION,standard title by hrf,human correction
0,Baggage Services Manager (12775),To manage the delivery of the end to end bagga...,Customer service manager,Airport operations coordinator
1,APOC and Resilience Lead (13485),The APOC and Resilience Lead is responsible fo...,0,Airport operations coordinator
2,Baggage Services Manager (12774),To manage the delivery of the end to end bagga...,Customer service manager,Airport operations coordinator
3,Baggage Services Manager (12776),To manage the delivery of the end to end bagga...,Customer service manager,Airport operations coordinator
4,Senior Engineering Resilience Manager (12698),Use market data,Engineering manager,Business continuity specialist
...,...,...,...,...
219,Rail Assessor/Trainer (12729),"To design, deliver and evaluate training for a...",Corporate trainer,Technical trainer
220,Utilities Performance Manager (12720),This is a key leadership role that impacts the...,Utilities manager,Utilities manager
221,Colleague Welfare and Logistics Co-ordinator (...,This role is working within the Colleague Welf...,Logistics specialist,Workplace coordinator
222,Colleague Welfare & Logistics Lead (13212),Heathrow is committed to putting our people at...,Logistics specialist,Workplace coordinator
223,Colleague Welfare & Logistics Manager (13210),This newly created role will work directly for...,Logistics specialist,Workplace coordinator

In [63]:
sum(df_check["standard title by hrf"]==df_check["human correction"])/len(df_check)

0.24553571428571427

In [64]:
df_check_title = pd.read_excel("data/output_titles_for Ruihao.xlsx")

In [67]:
sum(df_check_title["standard title by hrf "]==df_check_title["human correction"])/len(df_check_title)

0.5243829018663456

In [13]:
df_jobs = pd.read_csv("data/jobs_en_5k.csv")

In [14]:
inputs = df_jobs[["Original title", "std_title_name"]].rename(columns={"Original title": "job title", "std_title_name": "standard title"}).to_dict("records")

In [15]:
await check_title(text=str(inputs[0]))

'Forklift Operator'

In [16]:
gpt_titles = []
for sample in tqdm(inputs):
    gpt_title = await check_title(str(sample))
    gpt_titles.append(gpt_title)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3899/3899 [47:34<00:00,  1.37it/s]

In [17]:
df_jobs["gpt_title"] = gpt_titles

In [19]:
df_jobs.to_csv("data/4k_jobs_std_titles.csv", index=False)

In [27]:
(df_jobs["std_title_name"].str.lower() == df_jobs["gpt_title"].str.lower()).sum()/len(df_jobs)

np.float64(0.5604001025904078)

In [21]:
df_new = pd.read_csv("data/jobs_en_5k_with_new_approach_preds.csv")

In [31]:
df_new["gpt_title"] = df_jobs["gpt_title"]

In [39]:
(df_new["gpt_title"].str.lower() == df_new["std_title_name"].str.lower()).sum()/len(df_jobs)

np.float64(0.5604001025904078)

In [37]:
sum(df_new["std_title_name"].isnull())

351

In [44]:
df_check = pd.read_excel("data/output_titles_for Ruihao.xlsx")

In [50]:
sum(df_check["standard title by hrf "] == df_check["human correction"])/len(df_check)

0.5243829018663456

In [51]:
df_check

,raw title,standard title by hrf,human correction
0,Account Credit Manager I - Credit Management,Account manager,Credit manager
1,Account Credit Manager II - Credit Management,Account manager,Credit manager
2,Account Credit Manager III - Credit Management,Account manager,Credit manager
3,Account Investigator I - Risk and Compliance,Investigator,Fraud investigator
4,Account Investigator II - Risk and Compliance,Investigator,Fraud investigator
...,...,...,...
1656,Workforce Planning Coordinator I - Labor Relat...,Workforce planning specialist,HR administrator
1657,Workforce Planning Coordinator II - Labor Rela...,Workforce planning specialist,HR administrator
1658,Works Council Representative - Labor Relations...,Works council,Works council
1659,Worldwide Security Investigator I - Investigat...,Security investigator,Security investigator
1660,Worldwide Security Investigator II - Investiga...,Security investigator,Security investigator